# Generated by Django 2.0.2 on 2018-02-24 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('problems', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='problem',
            name='n_test_cases',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='problem',
            name='test_cases_uin',
            field=models.CharField(default='null', max_length=36),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='problem',
            name='timeout',
            field=models.FloatField(default=0.2),
        ),
        migrations.AlterField(
            model_name='problem',
            name='end',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='problem',
            name='language',
            field=models.CharField(choices=[('gcc', 'C -x99'), ('g++', 'C++ STL 11'), ('javac', 'JAVA 7'), ('node', 'JS'), ('python3', 'PYTHON 3')], default='C', max_length=10),
        ),
        migrations.AlterField(
            model_name='problem',
            name='start',
            field=models.DateField(),
        ),
    ]
